// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuygwpfhzvwkczuzpzga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1eWd3cGZoenZ3a2N6dXpwemdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NDAwNTksImV4cCI6MjA2MjIxNjA1OX0.LtlXOgcNu_TrAZr8s2VaWJq4oChXjp6sSmZlTxwnqaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);